### ISSUE TITLE
Refactor Unit Tests

### ISSUE THREAD

**Issue by jonathanio** [jonathanio/update-systemd-resolved#10]
There could be some improvements around the handling of the unit tests. Including:
- [x] Make `foreign_option_*` into an array: This will help with ordering, cleaning up after tests, and make it easier to work with and expand. Will need conversion out into the `foreign_option_*` variables however for internal processing, but will make the writing of tests easier and less error prone.
- [x] `dev` could probably be random alongside the `ifindex` value: the script can never be configured for it, and it should never know it, and so to set it in the tests has no real purpose.
- [x] Tests should only output in colour on colour-capable terminals.

**Comment by tomeon** [comment]
Done in #118.
