### ISSUE TITLE
AUR changes for upstream

### ISSUE THREAD

**Issue by ghost** [jonathanio/update-systemd-resolved#107]
Hi,

This issue is merely a report regarding some of the differences between this repo and the current [AUR package](https://aur.archlinux.org/packages/openvpn-update-systemd-resolved).

1. Per christoph.gysin, "Setting the path as instructed in the post install seems unnecessary." In the AUR setenv PATH has been deprecated/removed from all relevant files.
2. Per dimop, "openvpn 2.5.0-3 runs no longer scripts as root but as the user openvpn. Thus the D-BUS call to SetLinkDNS fails. My workaround is to authorize the user openvpn using a PolicyKit rule to update the DNS server in resolved." In the AUR a file named [openvpn-update-systemd-resolved.rules](https://aur.archlinux.org/cgit/aur.git/tree/openvpn-update-systemd-resolved.rules?h=openvpn-update-systemd-resolved) is provided and is stored in /usr/share/polkit-1/rules.d/00-openvpn-systemd-resolved.rules.

Further information can found on the [AUR](https://aur.archlinux.org/packages/openvpn-update-systemd-resolved).

**Comment by tomeon** [comment]
Thanks for this report.  Completed in #117.
