### ISSUE TITLE
Script for Mac OS

### ISSUE THREAD

**Issue by DJs3000** [jonathanio/update-systemd-resolved#113]
Hello! Can this script work with Mac OS? I have set up OpenVPN(community version) on Mac OS, a complex implementation with eToken. Everything works, but I can't redirect requests to DNS. On Linux, this script works perfectly!

**Comment by tomeon** [comment]
`systemd`, `systemd-resolved`, and (AFAIK) D-Bus are Linux-specific, so this script cannot work on macOS.
