### ISSUE TITLE
No script type specified

### ISSUE THREAD

**Issue by lrodorigo** [jonathanio/update-systemd-resolved#13]
Hi, I'm experiencing an issue using this script with OpenVPN 2.3.12, on Arch Linux with SystemD v231.

I can correctly connect to VPN, but my resolv.conf it's not changed.

Here's my connection log, which seems to correctly run  /etc/openvpn/update-systemd-resolved:

```
set 17 19:36:50 luiss-arch-port openvpn@luigi[8184]: TUN/TAP TX queue length set to 100
set 17 19:36:50 luiss-arch-port openvpn@luigi[8184]: do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
set 17 19:36:50 luiss-arch-port openvpn@luigi[8184]: /usr/bin/ip link set dev tun0 up mtu 1500
set 17 19:36:50 luiss-arch-port openvpn@luigi[8184]: /usr/bin/ip addr add dev tun0 local 192.168.255.6 peer 192.168.255.5
set 17 19:36:50 luiss-arch-port openvpn@luigi[8184]: /etc/openvpn/update-systemd-resolved tun0 1500 1541 192.168.255.6 192.168.255.5 init
set 17 19:36:50 luiss-arch-port openvpn@luigi[8184]: /usr/bin/ip route add <<remote_ip>>/32 via 192.168.0.254
set 17 19:36:50 luiss-arch-port openvpn@luigi[8184]: /usr/bin/ip route add 0.0.0.0/1 via 192.168.255.5
set 17 19:36:50 luiss-arch-port openvpn@luigi[8184]: /usr/bin/ip route add 128.0.0.0/1 via 192.168.255.5
set 17 19:36:50 luiss-arch-port openvpn@luigi[8184]: /usr/bin/ip route add 192.168.255.1/32 via 192.168.255.5
set 17 19:36:50 luiss-arch-port openvpn@luigi[8184]: Initialization Sequence Completed
```

Here's my vpn-client conf:

```
client
nobind
dev tun
key-direction 1
remote-cert-tls server
verb 4
remote <<server_url>> 1194 udp

key-direction 1

redirect-gateway def1

script-security 2
setenv PATH /usr/bin
up /etc/openvpn/update-systemd-resolved
down /etc/openvpn/update-systemd-resolved

client
nobind
dev tun
key-direction 1
remote-cert-tls server
verb 4
remote <<server_url>> 1194 udp

key-direction 1

redirect-gateway def1

script-security 2
setenv PATH /usr/bin
up /etc/openvpn/update-systemd-resolved
down /etc/openvpn/update-systemd-resolved
```

Here's script permissions:
`-rwxr-xr-x  1 root root 11191 17 set 18.24 update-systemd-resolved*`

My resolv.conf file keeps untouched after connection (and also the nslookup command is not using the DNS I specified server side).

Thanks for any kind of help.

Regards
Luigi 
Italy

**Comment by jonathanio** [comment]
Luigi,

Thank you for your feedback. Can you confirm that:
1. `systemd-resolve.service` is running; and
2. that your `/etc/resolv.conf` is a symlink `/run/systemd/resolve/resolv.conf`?

It should update the file, but it may not always be straight away. I have experienced delays and pauses in updating `/etc/resolve.conf` which is one of the reasons I wrote this script. :+1: 

Thanks.

**Comment by lrodorigo** [comment]
Hi!
You right, /etc/resolv.conf was a file instead of symlink.
If I create the symlink your script works well, but I'm experiencing some
dns related problems (eg. gmail.com not resolved).

If I manually edit resolv.conf with same dns server everything works well.
It should be some systemd-resolve related problem.

Many thanks

_Luigi R._

**Comment by jonathanio** [comment]
Luigi,

No problem. What is your `/etc/nsswitch.conf` settings? If you are using `system-resolved` with this script then it works best when you replace `dns` with `resolve` for the `hosts` option.

Retaining `dns` means that it'll use the `nameserver` options provided will function in a sort of failover way and there is no guarantee that your requests will go to the new nameserver. By using `resolve` instead, `systemd-resolved` will broadcast requests to all global DNS servers and take the first valid (or last negative) response, unless it has search or routing configured for domains, in which case they take priority.

Thanks.

**Comment by jonathanio** [comment]
@lrodorigo,

Do you have any feedback on this issue? If I don't hear from you in a few days, I'll close it as resolved.

Thanks.
