### ISSUE TITLE
Update for OpenVPN 2.4

### ISSUE THREAD

**Issue by mikken** [jonathanio/update-systemd-resolved#15]
Two problems with OpenVPN 2.4:

1. Error message when stopping service:
```
Broadcast message from systemd-journald@melforce (Mon 2016-12-12 22:24:49 MSK):

update-systemd-resolved[14692]: `busctl' exited with status 1
```

2. Config syntax changed (update README):
```
up ../update-systemd-resolved
down ../update-systemd-resolved
down-pre
```

**Comment by jonathanio** [comment]
@mikken,

Looking at the OpenVPN 2.4 [Man Page](https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage) both `down` and `down-pre` are still valid options, with `down-pre` the preferred option (to remove the DNS settings in a controlled manner before the tun/tap device is removed). Could you confirm please what needs to change in the README in order for this to work with OpenVPN 2.4?

I'll try and get OpenVPN 2.4 running on my system now to see if I can replicate these issues.

**Comment by mikken** [comment]
Yes, it doesn't work the old way:
```
openvpn[1866]: Options error: Unrecognized option or missing or extra parameter(s) in sinstr.conf:18: down-pre (2.4_rc1)
```

Did you carefully read the man page? `down-pre` takes no arguments, it only affects the order.

```
--down-pre
    Call --down cmd/script before, rather than after, TUN/TAP close. 
```

**Comment by jonathanio** [comment]
@mikken,

Ah yes I see what you mean now. Look back through 2.3 and 2.2 `down-pre` has never taken an argument. They must be tightening up the configuration processing, or we were using it in an undocumented way. I'll fix that now.

As to the `busctl` issue - I've installed 2.4rc1 on my laptop and the only issue I've seen so far is that `default` is no longer a valid option for `DNSSEC` - all other commands work correctly. Do you have the following in your configuration?

```
dhcp-option DNSSEC default
```

My logs:

```
Dec 12 20:15:34 gwyn openvpn[10727]: <14>Dec 12 20:15:34 update-systemd-resolved[10748]: Link `roadwarrior' coming up
Dec 12 20:15:34 gwyn openvpn[10727]: <14>Dec 12 20:15:34 update-systemd-resolved[10748]: Adding IPv4 DNS Server 8.8.8.8
Dec 12 20:15:34 gwyn openvpn[10727]: <14>Dec 12 20:15:34 update-systemd-resolved[10748]: Adding IPv4 DNS Server 8.8.4.4
Dec 12 20:15:34 gwyn openvpn[10727]: <14>Dec 12 20:15:34 update-systemd-resolved[10748]: Adding IPv6 DNS Server 2001:4860:4860::8888
Dec 12 20:15:34 gwyn openvpn[10727]: <14>Dec 12 20:15:34 update-systemd-resolved[10748]: Adding IPv6 DNS Server 2001:4860:4860::8844
Dec 12 20:15:34 gwyn openvpn[10727]: <14>Dec 12 20:15:34 update-systemd-resolved[10748]: Setting DNS Domain example.com
Dec 12 20:15:34 gwyn openvpn[10727]: <14>Dec 12 20:15:34 update-systemd-resolved[10748]: Adding DNS Search Domain example.net
Dec 12 20:15:34 gwyn openvpn[10727]: <14>Dec 12 20:15:34 update-systemd-resolved[10748]: Adding DNS Routed Domain example.org
Dec 12 20:15:34 gwyn openvpn[10727]: <14>Dec 12 20:15:34 update-systemd-resolved[10748]: Setting DNSSEC to no
Dec 12 20:15:34 gwyn openvpn[10727]: <14>Dec 12 20:15:34 update-systemd-resolved[10748]: SetLinkDNS(8 4 2 4 8 8 8 8 2 4 8 8 4 4 10 16 32 1 72 96 72 96 0 0 0 0 0 0 0 0 136 136 10 16 32 1 72 96 72 96 0 0 0 0 0 0 0 0 136 68)
Dec 12 20:15:34 gwyn openvpn[10727]: <14>Dec 12 20:15:34 update-systemd-resolved[10748]: SetLinkDomains(8 3 example.com false example.net false example.org true)
Dec 12 20:15:34 gwyn openvpn[10727]: <14>Dec 12 20:15:34 update-systemd-resolved[10748]: SetLinkDNSSEC(8 no)
```

**Comment by mikken** [comment]
Busctl error happens when I do privilige drop:
```
user openvpn
group openvpn
```

No problems during startup or during operation, except for `logger` (during startup):
```
openvpn[3146]: logger: send message failed: Operation not permitted
```

**Comment by jonathanio** [comment]
@mikken,

OK. I see what's happening now and can replicate it myself. It seems I forgot to add the privilege drop to my client (it's enabled on the server, but this script isn't run there) so I didn't see it until now.

I think I'll have to put a privilege check on the `down()` call as a minimum - there's no way to resolve this other than to have it not run on disconnect. At least with `systemd-resolved.service` there isn't a real difference between running the script and not running the script. The link settings technically revert anyway when the device is dropped. Allowing the script to do it is a little cleaner and makes it easier to add additional steps in the future if required. However, that will need additional consideration in the future now.

**Comment by jonathanio** [comment]
@mikken,

I've made some changed and prepared a pre-release for you on PR #16. Can you confirm this resolves your issues and if so I'll put out a release.

Thanks.

**Comment by mikken** [comment]
Yes, it's resolved.
