### ISSUE TITLE
Please document required system tools

### ISSUE THREAD

**Issue by piotr-dobrogost** [jonathanio/update-systemd-resolved#18]
For example update-systemd-resolved.sh uses `ip` command which on Fedora is located at /usr/sbin/ip yet README suggests setting PATH to /usr/bin.
Generally, in order to establish how PATH should look like one should know which system tools are being used.

**Comment by jonathanio** [comment]
@piotr-dobrogost,

Thank you for the bug report. Appreciated, the `PATH` environmental variable, as provided, won't work on RedHat-based distributions. This was developed on an Arch-based system, which does away with the bin/sbin split, as well as usr/no-usr structure (everything is in /usr/bin), which is also the same way that Debian is going (where I know this script has also been tested as-is so far).

I'll fix the documentation and issue a new release in the next few days.

**Comment by mgu** [comment]
On Debian systems, `bash` is put in `/bin`, not in `/usr/bin`

**Comment by piotr-dobrogost** [comment]
@mgu 
And `/usr/bin` is not symlinked to `/bin`?

**Comment by mgu** [comment]
On my Debian Stretch, `/bin/bash` is a regular file and there is no `/usr/bin/bash`
