### ISSUE TITLE
Link to the source documentation of "dhcp-option" commands

### ISSUE THREAD

**Issue by piotr-dobrogost** [jonathanio/update-systemd-resolved#19]
At https://github.com/jonathanio/update-systemd-resolved#usage there's a table with `dhcp-options` set by OpenVPN but these options are not mentioned in OpenVPN's documentation at https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage.
It would be useful to have a link to the source documentation for these options.

**Comment by jonathanio** [comment]
@piotr-dobrogost,

When you talk about source documentation, do you mean about the commands that I call within OpenVPN (i.e. `push`/`dchp-options`) or documentation about what each of the `dhcp-options` means (such as `DNS`, `DOMAIN`, ...)?

**Comment by piotr-dobrogost** [comment]
The latter one. I just couldn't find anything on subject in OpenVPN's docs.

**Comment by jonathanio** [comment]
I've completed some research, and aside from there now being some documentation for `DNS` and `DOMAIN` under the `dhcp-option` command-line argument, there is no real information about the origins of those and others I have used. Although `DOMAIN-SEARCH` is just the full name for DHCP option 119 anyway, `DOMAIN-ROUTE` and `DNSSEC` are just custom names I have implemented to enable the configuration of the appropriate settings and are valid only in combination with this script and `systemd-resolved`.

Given that I have included details on the page for each of these options, I'll close this as-is. I am always open to disagreement, so if you would like more information, please re-open it.
