### ISSUE TITLE
Installation location inconsistencies

### ISSUE THREAD

**Issue by flungo** [jonathanio/update-systemd-resolved#23]
The `Makefile` installs the script to `/etc/openvpn/scripts/update-systemd-resolved` but the AUR package installs to `/etc/openvpn/update-systemd-resolved` and the documentation in the `README.md` also assumes that this is where the script is installed to. I suggest that either the `Makefile` is updated or the AUR package and documentation are so that the installation location and instructions are consistent regardless of what method is used for installation.

**Comment by jonathanio** [comment]
I think I'm happy for this to be corrected. I think that the path may be something that is Debian-specific? Do you want to do this, or would you like me to?

**Comment by flungo** [comment]
Which would you prefer:

- `/etc/openvpn/scripts/update-systemd-resolved`
- `/etc/openvpn/update-systemd-resolved`

I think the later would be easier to go with as it would only require changing the `Makefile` and would not break anything for installations already made through the AUR package, but the former might be considered neater.

It's a trivial change so feel free to make it yourself, but also happy to check through and make sure there are no other places that need changing and submit a PR for the changes.

**Comment by jonathanio** [comment]
Agreed - latter! :+1: I'll sort something out in the next few days.
