### ISSUE TITLE
Not a recognized DHCP setting: 'DISABLE-NBT'

### ISSUE THREAD

**Issue by ghost** [jonathanio/update-systemd-resolved#24]
I have pasted this into my ovpn file:

```
script-security 2
up /etc/openvpn/scripts/update-systemd-resolved 
down-pre /etc/openvpn/scripts/update-systemd-resolved
push "dhcp-option DNS 8.8.8.8"
```
I want to set the DNS Server to 8.8.8.8.
But when i run the openvpn file, i get this output. 

```
Wed Mar 15 13:02:55 2017 /etc/openvpn/scripts/update-systemd-resolved tun0 1500 1570 25.0.8.6 255.255.255.0 init
<14>Mar 15 13:02:55 update-systemd-resolved[5469]: Link 'tun0' coming up
<14>Mar 15 13:02:55 update-systemd-resolved[5469]: Adding IPv4 DNS Server 25.0.0.1
<12>Mar 15 13:02:55 update-systemd-resolved[5469]: Not a recognized DHCP setting: 'DISABLE-NBT'
<14>Mar 15 13:02:55 update-systemd-resolved[5469]: SetLinkDNS(12 1 2 4 25 0 0 1)
```

I don't know why the dns server is always set to 25.0.0.1 .

Would be nice if you could help

**Comment by piotr-dobrogost** [comment]
`Not a recognized DHCP setting:` log entry is only informational and there's nothing to worry about here. DNS server's ip is being set probably as a consequence of OpenVPN server pushing such an option to the client. You can see all settings pushed by the server when you run OpenVPN client from command line, without using any deamon related options and with high enough log verbosity level (5 should be ok). In client config you want `dchp-option DNS 8.8.8.8`; notice lack of `push` and quotation marks.

**Comment by jonathanio** [comment]
@Philluminati: Agreed with @piotr-dobrogost. If you make the changes described above and ignore the notice given you should see `8.8.8.8` added as a DNS server when you connect. However, it should also be noted that `systemd-resolved` does not exclusively use that server in the way that updating `/etc/resolve.conf` does. It will add `8.8.8.8` alongside `25.0.0.1` to `systemd-resolved` and will use those alongside any local DNS servers set by your LAN's DHCP or SLAAP configuration, with the first to respond often being the used over the others.

If you're still noticing problems, please let me know.
