### ISSUE TITLE
Can't Enable/Start the Service

### ISSUE THREAD

**Issue by thatotheritguy** [jonathanio/update-systemd-resolved#27]
It always fails to execute. no log files, as....well..it fails to execute. 

Platform: Centos7

**Comment by jonathanio** [comment]
Have you run `openvpn` manually on the command line and viewed the output from that? There's some discussion in #25 around the issue of using `--id=$$` inside the script to report the PID of the parent process, not the `logger` process, and under some privilege drop situations which `systemd` enables, this is not a permitted option. That could explain why you're not seeing logging information either.

**Comment by thatotheritguy** [comment]
I can try that tonight, but I am unsureif running it from openvpn would yield anything. I am on the setup process, running `systemctl enable systemd-resolved.service` I receive an error about no such file/dir. I read #23 and tried to verify I wasn't in the wrong dir, but I seem to be ok their. 

EDIT: when I return home today, I will get screen shots of the errors and the journalctl.

**Comment by jonathanio** [comment]
Thanks. If you run `openvpn --config /path/to/config.conf` as `root` then it should just output its logs to the terminal. If there are restrictions in place which are causing issues for the script then by running it from the command-line rather than via `systemd` should remove those restrictions.

**Comment by thatotheritguy** [comment]
When I run that command under root I receive this:

> [root@$HOSTNAME openvpn]# openvpn --config /etc/openvpn/$configfilename.conf
Options error: Unrecognized option or missing parameter(s) in /etc/openvpn/$configfilename.conf:27: hosts: (2.3.14)
Use --help for more information.

>

**Comment by thatotheritguy** [comment]
Now that I am looking closer, I dont have a /etc/nsswitch.conf. I must be missing a prerec on this. I followed your directions on this, am I missing something here (It wouldnt surprise me)

**Comment by thatotheritguy** [comment]
Ok. I think I have it figured out. I had too swapped the /nsswitch.conf and the openvpn conf config changes around, for what ever reason (I guess I had one too many ciders that night. 

Cheers and thanks!
