### ISSUE TITLE
Not a recognized DHCP setting: 'ADAPTER_DOMAIN_SUFFIX

### ISSUE THREAD

**Issue by JoshDobbin** [jonathanio/update-systemd-resolved#38]
When using this tool in conjunction with OpenVPN I get an error:

Not a recognized DHCP setting: 'ADAPTER_DOMAIN_SUFFIX <domain>

That prevents me from updating the default search domain.

**Comment by jonathanio** [comment]
@JoshDobbin,

I've added the support as requested. This will go out shortly in a formal release.
