### ISSUE TITLE
pre-down is an "Unrecognized option or missing parameter"

### ISSUE THREAD

**Issue by pid1** [jonathanio/update-systemd-resolved#4]
It looks like this was updated a couple days ago, so I may be doing something wrong with my configuration, but openvpn isn't recognizing pre-down as valid. It is (predictably) not a valid route-pre-down script, and a simple down fails out since tun0, as expected, does not exist. I could not find a mention of pre-down in the man pages anywhere.

I have not had much time to poke at the manual, but could we write a complementary route-pre-down to handle this?

OpenVPN 2.3.11
iproute2 4.7.0
systemd 231

**Comment by jonathanio** [comment]
Looking at the OpenVPN Man page, it's `down-pre` rather than `pre-down`. Could you give that a go and let me know if it works for you? If so, I'll update the configuration and documentation.
