### ISSUE TITLE
Add common file

### ISSUE THREAD

**Issue by rightaway** [jonathanio/update-systemd-resolved#41]
Would you consider adding a file containing the extra config needed?

```
script-security 2
setenv PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
up /etc/openvpn/scripts/update-systemd-resolved
down /etc/openvpn/scripts/update-systemd-resolved
down-pre
```

So that when installing the Arch AUR package, instead of needing to change any `.conf` files or add all those separate config parameters to the `openvpn` command, we could just add `--config ../scripts/common.conf` (assuming the file is in `/etc/openvpn/scripts/common.conf`) to the end of the `ExecStart` line in `/usr/lib/systemd/system/openvpn-client@.service` and it would work. That way the file would be kept up-to-date here.

Or is this something I need to ask to the AUR package maintainer?

**Comment by jonathanio** [comment]
@rightaway,

You'll be pleased to know I'm the maintainer of the AUR package too!

I've taken the time to think about your request, and while, on the whole, it's a reasonable idea, it runs the risk of:

1. Putting some of the onus on the configuration of OpenVPN itself onto my script, which I feel is a little bit beyond the purpose of what I'm trying to do; and
2. Will diverge the standard configuration on Arch compared to other distributions. I've made quite a few changes to packages and build scripts recently to bring everything together.

At the moment I'd rather not add a common configuration file into the script or the package, but I am open to discussion on the matter.

A bonus point - don't edit the `/usr/lib/systemd/system/openvpn-client@.service` directly as the configuration will be overridden on an update to `openvpn`. Instead run `systemctl edit openvpn-client@.service` and write only:

```
[Service]
ExecStart=/usr/bin/openvpn --suppress-timestamps --nobind --config %i.conf -- config /etc/openvpn/scripts/common.conf
```

That way you override only what you need too and it'll survive package updates.

**Comment by rightaway** [comment]
Wouldn't the common file be needed on even non Arch systems that are using systemd?

Thanks for the tip. Do you know where that `edit` command will create that override file? I'm trying to provision a system.
