### ISSUE TITLE
cant connect after running make

### ISSUE THREAD

**Issue by tetoNidan** [jonathanio/update-systemd-resolved#42]
I read through your guide and gave it a whirl. 

Using ubunjtu 16.04.
Openvpn v: 2.3.10
iprout2 v: 4.3.0
systemd: 229

I replaced myhostname with my computers hostname and updated the /etc/nsswitch.conf so it looks like

hosts: files resolve dns myHOSTNAME

service systemd-resolved status show that the service is running.

Looks like network-manager is running and connected just fine. Gussing the dns isnt getting resolved. at least I dont think it is. 

How would I go about fixing the issue or removing what was made/done in the makefile? 

Thanks.

**Comment by jonathanio** [comment]
If you run `make` all that happens is that the script is installed to `/etc/openvpn/scripts/update-systemd-resolved`. It makes no changes to any configuration on the system, including `nsswitch.conf` nor any current OpenVPN configuration. All it does afterwards if give you the information you need to make the changes needed yourself.

You have added `resolve` to `nssswitch.conf`, which will enable lookup, but `myhostname` is not a string to be changed but is another lookup that just returns your machines IP if the lookup matches the hostname of the machine itself. That may be breaking DNS is NSS cannot correctly process the configuration.

Beyond that, you will need to ensure that the script is activated as part of your OpenVPN configuration. `make info` will provide that, or read the `README.md` for full details.

**Comment by tetoNidan** [comment]
Sorry for the late response. Been fighting a cold. 

I see now what was going on, network-manager was interfering. Operator error. 

Thank you very much sir.
