### ISSUE TITLE
Invalid device name: 'tun0'

### ISSUE THREAD

**Issue by jamsch0** [jonathanio/update-systemd-resolved#44]
Hi,

I get the above error when trying to start the openvpn-client service. When using `update-resolv-conf.sh` instead it starts up correctly (ignoring DNS issues).

**Comment by jonathanio** [comment]
@jchapman127,

If you are receiving that error, that suggests that the device hasn't been created by OpenVPN before the script is run, which is unusual. The script doesn't assume any device name or configuration as that is all provided by the daemon once the connection has been established. Do you have any outputs or logfiles available for this issue?

**Comment by jamsch0** [comment]
Sorry, just got back around to this. I've just upgraded all the packages on my system and now this is working absolutely fine :man_shrugging:
