### ISSUE TITLE
Can Not Enable and Start systemd-resolved.service

### ISSUE THREAD

**Issue by calvinlevy** [jonathanio/update-systemd-resolved#47]
Hi @jonathanio, using CentOS Linux release 7.5.1804 I am not successful enabling and starting systemd-resolved.service.  I will recap highlights in my quest:

1.  Follwed instructions [here](https://github.com/jonathanio/update-systemd-resolved).  Receiving Failed to execute operation: No such file or directory
2.  Updated /etc/nsswitch.conf as follows:        hosts:      files resolve dns myhostname
3.  Reviewed issues #46, #45, #37, #27 and #25.   #23 speaks to the issue but the conclusion didn't specifically outline the fix.  (Unless I am over looking an obvious comment.)

Any guidance?

I did confirm resolution via global DNS provider in local LAN while connected via OpenVPN client using:  nslookup (hostname) (dns server)

**Comment by jonathanio** [comment]
@calvinlevy,

What is the output from `systemctl status systemd-resolved.service`? I've never had any issues with trying to run `systemd-resolved` in the past, so if you can provide me with any information about its attempt to run I can try and investigate for you.

**Comment by jonathanio** [comment]
Closing as no additional detail has been provided.
