### ISSUE TITLE
Multiple DNS domains

### ISSUE THREAD

**Issue by fwannmacher** [jonathanio/update-systemd-resolved#56]
I have a case where there are 2 DNS Servers, lets say, 192.168.20.20 and 10.1.10.10. There are also 2 domains domain1.local and domain2.local. When the script resolves it creates a link between both servers and a link for the first domain. But it won't link the second domain.

Following the log:
Mon Nov  5 01:10:23 2018 /etc/openvpn/scripts/update-systemd-resolved tun0 1500 1560 10.15.1.2 255.255.255.0 init
<14>Nov  5 01:10:23 update-systemd-resolved: Link 'tun0' coming up
<14>Nov  5 01:10:23 update-systemd-resolved: Adding IPv4 DNS Server 192.168.20.20
<14>Nov  5 01:10:23 update-systemd-resolved: Adding IPv4 DNS Server 10.1.10.10
<14>Nov  5 01:10:23 update-systemd-resolved: Setting DNS Domain domain1.local
<14>Nov  5 01:10:23 update-systemd-resolved: SetLinkDNS(11 2 2 4 192 168 20 20 2 4 10 1 10 10)
<14>Nov  5 01:10:23 update-systemd-resolved: SetLinkDomains(11 1 domain1.local false)

Any ideas?

**Comment by jonathanio** [comment]
Can you provide your `dhcp-options` configuration lines? You cannot have more than one entry on a line, and use of `dhcp-options DOMAIN` is limited to the last provided entry as this is for the primary search domain on a line, not a list of all domains to route through to the private servers.

If you want to just route the DNS, use `dhcp-options DOMAIN-ROUTE` instead (or add the secondary domain as `DOMAIN-SEARCH` to search if the primay domain fails).

**Comment by fwannmacher** [comment]
Those options are server side right? In this case I have no access to them.

**Comment by fwannmacher** [comment]
That is not a issue from your script. I got the replies and there is no push reply for the second domain.

Thanks for the help.

**Comment by jonathanio** [comment]
No problem. Thanks for letting me know!
