### ISSUE TITLE
Add some configuration feature

### ISSUE THREAD

**Issue by mikken** [jonathanio/update-systemd-resolved#6]
Hello,
I'd like to configure two things if possible:
1. Add DNS domains on the link as routing domains only, not search domains
2. Ability to set DNSSEC= for the link

**Comment by jonathanio** [comment]
@mikken,

The routing/search domain option is already provided:

``` yaml
dhcp-option DNS 10.2.3.1
dhcp-option DOMAIN example.local
dhcp-option DOMAIN-SEARCH example.com
```

On review it is a little counter-intuitive: Here, `example.co.uk`, set by `DOMAIN` is a search domain (and will be routed to the server `10.2.3.1`). `example.com`, set by `DOMAIN-SEARCH` is a routed domain only and will not be appended to any bare hostnames, only routed through to `10.2.3.1`.

For the existing `update-resolve-conf` and `update-systemd-network` scripts, `DOMAIN` and `DOMAIN-SEARCH` are treated the same: They all are search domains and added as a single list for searching so the precedent is not clear here as to which is a search or routed domain in the `systemd` sense. IIRC I assumed `DOMAIN` to be the domain name of the link, and therefore the default domain for searching (although you can add multiple `DOMAIN` options and they will all be searched), while `DOMAIN-SEARCH` is just for domains to be routed.

I am option to suggestions and discussion on this, and I think there are three options:
1. Keep as-is;
2. Swap around the meaning of `DOMAIN` and `DOMAIN-SEARCH` (routed only and routed plus search for bare names, respectively); or
3. Combine `DOMAIN` and `DOMAIN-SEARCH` to mean search domains for the link, in keeping with how `update-resolve-conf` and `update-systemd-network` treats them, and add `DOMAIN-ROUTE` as a `systemd`-specific configuration only understood by this script.

Nonetheless, additional documentation on the options accepted and their meaning is needed as well.

As for `DNSSEC`, I think that's a reasonably easy option to implement. It should just need a few new tests, a new `process_dnssec()` function and some additional logic in `up()`. I'll see if I can add that over the next few days.

**Comment by jonathanio** [comment]
@mikken,

I've actually had a little bit of time free through this morning and early afternoon and have managed to add in the required code needed to support DNSSEC. The `feature/dnssec-support` branch has the code and it would be good if you could give it a try and see if it works as expected for you?

You will need to add the following in your OpenVPN configuration to force DNSSEC to be enabled on the link:

``` yaml
dhcp-option DNSSEC yes
```

**Comment by mikken** [comment]
I think option 2 is good (DOMAIN-SEARCH for search+routing domain and DOMAIN for pure routing). 
I tested feature/dnssec-support and the script exits with error code 1 if I add this dhcp-option. openvpn exits as well. Removing dhcp-option makes the connection work again.
This is systemd v231.

The script fails here:

```
    info "SetLinkDNSSEC(${busctl_params[*]})"
    busctl_call SetLinkDNSSEC 's' "${busctl_params[@]}" || return 3
```

(exit code replaced with 3 to test)

busctl call arguments look good, I added some debug output::

```
      echo ${if_index} > /etc/openvpn/test
      echo ${dns_sec} >> /etc/openvpn/test
      echo ${busctl_params[*]} >> /etc/openvpn/test
```

And file "test" contains:

```
20
yes
20 yes
```

**Comment by jonathanio** [comment]
Reading more on the subject, including `resolv.conf(3)` as well as [RFC1533](https://tools.ietf.org/search/rfc1533) and [RFC3397](https://tools.ietf.org/search/rfc3397) there just isn't the equivalent DHCP option for only routing DNS traffic via this interface/server. In theory, `DOMAIN` implies `DOMAIN-SEARCH` as it is both the local default suffix and the search domain, while `DOMAIN-SEARCH` if provided, would override this.

For *nix-based systems which rely on the standard `resolv.conf` the practice is to see `DOMAIN` and `DOMAIN-SEARCH` as equal: They both append to the search list, and there is no understanding of only routing that domain to these specific servers but not searching with each of them as a component.

Based on this my inclination is to take the third option: Merge the meaning of `DOMAIN` and `DOMAIN-SEARCH` but with the added logic that there can only be a single `DOMAIN` setting (LIFO) and then allow "unlimited" `DOMAIN-SEARCH` options. From that, the `DOMAIN` value will be the primary search domain presented to `systemd-resolved` and all other `DOMAIN-SEARCH` options appended in the order received (FIFO). Finally, `DOMAIN-ROUTED` will be added to support the new option available here and run a heterogeneous environment.

This option is the most compatible with all current other implementations, including Windows, and clearly defines the purpose of the setting with transparent fallback should it not be understood (i..e all other systems will just route _all_ queries to the default nameserver, or the secondary, etc., should that fail).

I just feel that to change the meaning of `DOMAIN` will introduce backwards incompatible changes which can alter domain lookups in non-obvious ways, and while the use of this script at the moment implies reasonable technical knowledge, this may not always be the case.

**Comment by jonathanio** [comment]
Looking more specifically at the error, it requires the smallest of changes. I forgot to add the _i_nteger parameter to the type statement for `busctl`, so it was only expecting a single string argument and I provided it with two. I've pushed a fix and it should now work:

``` shell
# busctl call org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.resolve1.Manager SetLinkDNSSEC is 4 yes
$ dbus-send --print-reply --system --type=method_call --dest=org.freedesktop.resolve1 /org/freedesktop/resolve1/link/_34 org.freedesktop.DBus.Properties.GetAll string:''
(snip)
      dict entry(
         string "DNSSEC"
         variant          string "yes"
      )
(snip)
```

**Comment by mikken** [comment]
Cool, DNSSEC option works now.

**Comment by jonathanio** [comment]
Brilliant. I've two more branches to make the logic changes and update the documentation. I'll get this released this week. Thanks for the idea!
