### ISSUE TITLE
authselect user-nsswitch.conf in Fedora

### ISSUE THREAD

**Issue by almereyda** [jonathanio/update-systemd-resolved#61]
Fedora is offering `authselect` as configuration tool for `/etc/nsswitch.conf`. Using it would involve putting custom configuration into `/etc/authselect/user-nsswitch.conf`.

* [Issue #1815: F28 System Wide Change: Make authselect default tool instead of authconfig - fesco - Pagure.io](https://pagure.io/fesco/issue/1815)
* [Design Document: nsswitch.conf modification · pbrezina/authselect Wiki](https://github.com/pbrezina/authselect/wiki/Design-Document:-nsswitch.conf-modification)
* [User:Pbrezina/Authselect and packages that modifies nsswitch - Fedora Project Wiki](https://fedoraproject.org/wiki/User:Pbrezina/Authselect_and_packages_that_modifies_nsswitch)
* [Give packages way to modify nsswitch.conf · Issue #77 · pbrezina/authselect](https://github.com/pbrezina/authselect/issues/77)

This has been found after seeing erranous behaviour of DNS resolution after introducing these scripts and implied changes to the system.

More is documented in

* [DNS resolution and connectivity issues - Desktop - Fedora Discussion](https://discussion.fedoraproject.org/t/dns-resolution-and-connectivity-issues/1100)

**Comment by piotr-dobrogost** [comment]
How is this related to this project?

**Comment by almereyda** [comment]
This project suggests one to manipulate `nsswitch.conf` for activating the `resolv` module in a way that is not compliant with `authselect`, if present and activated.

**Comment by jonathanio** [comment]
Although there isn't anything, script-wise, I can do about `authselect`, I have nonetheless added notes in the documentation on using the script on Fedora 28 or later, recommending the stub resolver method over NSS changes. That should help any confusion around this.
