### ISSUE TITLE
DNS servers not set when multiple are pushed in same command

### ISSUE THREAD

**Issue by draxxris** [jonathanio/update-systemd-resolved#69]
When an openvpn server pushes, via `dhcp-option "DNS 8.8.8.8 1.1.1.1"` update-systemd-resolved does not set any DNS servers. The previously used script `update-resolv-conf` did properly handle such a server-side push command.

This can be fixed by changing the server to use two `dhcp-option DNS` commands, but I don't have access to alter the server in my use cases.

The fix should be to iterate over all arguments in a `dhcp-option DNS` command.

**Comment by draxxris** [comment]
Actually it looks like openvpn 2.4+ no longer pushes DNS to the up-down script if it "malformed".

**Comment by jonathanio** [comment]
@polski-g Actually, I didn't know that, but I think with Windows and Mac, those clients only support the single value, hence why I kept it the same. Good to know about OpenVPN's processing nonetheless. So thank you for that at least.

**Comment by draxxris** [comment]
For anyone looking into this in the future, the upstream ticket is here: https://community.openvpn.net/openvpn/ticket/809

> ... used to ignore the rest, while in 2.4.0, we actually tell people that there are too many arguments
