### ISSUE TITLE
Duplicate log output when running openvpn with systemd service

### ISSUE THREAD

**Issue by VannTen** [jonathanio/update-systemd-resolved#81]
Hi,

First, thanks for you script, it works great :)

I just noticed a little inconvenience, which happens to me when running openvpn through the openvpn-client@.service which is shipped with openvpn.

```
Jun 11 16:40:29 hostname update-systemd-resolved[116319]: Link 'tun0' coming up
Jun 11 16:40:29 hostname openvpn[116319]: <14>Jun 11 16:40:29 update-systemd-resolved: Link 'tun0' coming up
```
As you can see the action logged by the script are duplicated.
I think it can be avoided by removing the `-s` option to logger in the log() function, but I guess that would break logging when not runned that way ?
Maybe there is way to check ?

**Comment by tomeon** [comment]
Fixed in #115.  Thanks, @VannTen!
