### ISSUE TITLE
cannot access '/run/systemd/resolve/stub-resolv.conf': No such file or directory

### ISSUE THREAD

**Issue by queglay** [jonathanio/update-systemd-resolved#82]
I'm interested to see if I can get DNS working on my ubuntu 16.04 gateway into an AWS access server.

It appears the stub resolver is the recommended method (instead of NSS) for Ubuntu 16.04
I've read the docs, and I must be missing something, because /run/systemd/resolve/stub-resolv.conf doesn't exist.  Should I be using this method for Ubuntu 16?

**Comment by schnuffle** [comment]
On 16.04 systemd-resolved is not active by default, you need to activate it

Regards

Schnuffle

**Comment by queglay** [comment]
Thanks I will try this out.
