### ISSUE TITLE
Is there a way to specify a wildcard domain in "dhcp-option DOMAIN" ?

### ISSUE THREAD

**Issue by max-k** [jonathanio/update-systemd-resolved#93]
I tried to specify it using systemd-resolved syntax (~domain.tld) but it is converted to a simple domain name with a utf-8 character code prefix (\126domain.tld).

It doesn't to come from this script but rather from systemd-resolved DBUS interface but I ask my question just to know as been successful in the process.

Thank you very much.

**Comment by worldowner** [comment]
~ is added when server sends DOMAIN-ROUTE instead of DOMAIN.

**Comment by tomeon** [comment]
@max-k -- closing this; please reopen if using `dhcp-option DOMAIN-ROUTE domain.tld` does not work for you.
